version: "3.7"
services:
    # image project
    laravel_8:
        build: 
            args: 
                user: laravel
                uid: 1000
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        command: ["sh", "-c", "/usr/local/bin/set_env.sh && php-fpm"]
        volumes:
            - ./:/var/www
        environment:
            - APP_ENV=local
        networks: 
            - laravel    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 80:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel

networks: 
    laravel:
        driver: bridge
